apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazar-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bazar-api
  template:
    metadata:
      labels:
        app: bazar-api
    spec:
      containers:
        - name: bazar-api
          image: europe-west9-docker.pkg.dev/project-6ead5f33-15fd-443c-817/bazar-api-repo/bazar-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bazar-api-secrets
                  key: jwt_secret
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: bazar-api-secrets
                  key: email_user
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: bazar-api-secrets
                  key: email_pass
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
